runtime: python27
version: 1
api_version: 1
application: fctv-player-1127
threadsafe: true

handlers:
- url: /
  static_files: static/clicks.html
  upload: static/clicks.html
  secure: always
  expiration: "1d"
  http_headers:
    X-Content-Type-Options: nosniff
    Strict-Transport-Security: max-age=31536000; includeSubDomains; preload

- url: /static
  static_dir: static
  secure: always
  expiration: "1d"
  http_headers:
    X-Content-Type-Options: nosniff
    Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
